import {
	CLOSED,
	OPEN,
	WHITE,
	BLACKOPENING_POSITIONS,
	NEW_GAME_ID,
	JOIN_GAME_ID,
	OPEN_GAMES_MENU_ID,
	JOIN_GAME_BUTTON_ID,
	JOIN_GO_BACK_BUTTON_ID,
	MOVE_FROM_MENU,
	MOVE_TO_MENU,
	MOVE_SELECT_GAME_ID
} from "./gameConstants.js";

type GameState = OPEN | CLOSED
type PawnColors = WHITE | BLACK
type ComponentCustomIds  = NEW_GAME_ID | JOIN_GAME_ID | OPEN_GAMES_MENU_ID| JOIN_GAME_BUTTON_ID | JOIN_GO_BACK_BUTTON_ID | MOVE_FROM_MENU | MOVE_TO_MENU | MOVE_SELECT_GAME_ID

export const gameConstants =  {
	OPEN,
	CLOSED, 
	BLACK, 
	WHITE, 
	OPENING_POSITIONS, 
	NEW_GAME_ID,
	JOIN_GAME_ID,
	OPEN_GAMES_MENU_ID,
	JOIN_GAME_BUTTON_ID,
	JOIN_GO_BACK_BUTTON_ID,
	MOVE_FROM_MENU,
	MOVE_TO_MENU,
	MOVE_SELECT_GAME_ID
}

export {
	GameState, 
	PawnColors, 
	ComponentCustomIds,
}